# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(verbose_name='ID поста вконтакте')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('text_md5', models.SlugField(unique=True, verbose_name='MD5 сообщения')),
                ('like_count', models.IntegerField(verbose_name='Количество лайков')),
                ('repost_count', models.IntegerField(verbose_name='Количество репостов')),
                ('subscriber_count', models.IntegerField(verbose_name='Количество подписчиков группы')),
                ('publication_time', models.DateTimeField(verbose_name='Время публикации')),
                ('is_repost', models.BooleanField(default=False, verbose_name='Репост сделан')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True, verbose_name='Адрес паблика')),
                ('last_parse', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего парса')),
            ],
            options={
                'verbose_name': 'Паблик',
                'verbose_name_plural': 'Паблики',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposter.Public'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('public', 'vk_id')]),
        ),
    ]
