# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publication_time',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_time',
            field=models.DateTimeField(db_index=True, verbose_name='Время публикации'),
        ),
    ]
