# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='subscriber_count',
            field=models.IntegerField(default=0, verbose_name='Количество подписчиков'),
        ),
    ]
