# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposter', '0002_auto_20160603_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время репоста'),
        ),
    ]
